name: Linting

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint isort black
    - name: Check import order
      run: |
        isort . --check-only
    - name: Black formatting
      run: |
        black . --check --verbose --diff --color --line-length 88
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
